### ISSUE TITLE
stack-frame-resolver v0.1.4 does not contain script files

### ISSUE THREAD

**Issue by darrenscerri** [Timer/stack-frame#6]
`stack-frame-resolver` v0.1.4 does not contain script files. Also package is not on Github.

**Comment by Timer** [comment]
Hmm, seems like a botched `npm publish`; I wonder how that happens ...

**Comment by Timer** [comment]
Should've resolved this in v0.1.5. Package is off Github because it's deprecated and shouldn't be used anymore (sorry you ran into this; no one but CRA is depending on it anyway) -- it's a legacy package until redbox2 is merged. Sorry about this!

**Comment by darrenscerri** [comment]
Thanks! All good now!
